### ISSUE TITLE
set the alarm threshold as variable for every wallet 

### ISSUE THREAD

**Issue by hossnys** [threefoldtecharchive/tfgrid_monitoring_bot#11]
as many of wallets doesn't need to have large amount of tokens to be there to do it's job but for example mainnet ops wallet needs to be refunded at high amount of tftsas many deployments running using it .

**Comment by A-Harby** [comment]
Verified, threshold is now a variable can be adjusted as wanted.

![image](https://user-images.githubusercontent.com/109473873/204518226-5c28faea-bf29-41c7-bd08-c866bf9f76f9.png)
