### ISSUE TITLE
add wallet name as variable in wallets.json and in sent messages

### ISSUE THREAD

**Issue by hossnys** [threefoldtecharchive/tfgrid_monitoring_bot#13]
-  we need to be able to distinguish which wallet this address belong to , so a wallet name need to be added in wallets.json and sent in the alert message .

**Comment by A-Harby** [comment]
Verified,
Wallet name is now a variable can name as wanted.
![image](https://user-images.githubusercontent.com/109473873/204518416-8b12f1e8-b17d-419a-af29-546f2b5db7f5.png)
