### ISSUE TITLE
Only one net is enough, other should be optional 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_monitoring_bot#19]
## Describe the bug

Can you make it optional to add mnemonics of more than one net(only one is enough), cause If the user have only one twin, it is not necessary to add both net (which he wouldn't be using it).  

## To Reproduce
remove mnemonics in one of the net, or leave it empty.

## Screenshots
![image](https://user-images.githubusercontent.com/109473873/204529518-815bbf2f-76bf-4592-902d-1589d117d259.png)

**Comment by rawdaGastan** [comment]
I asked about it. They need it to have both testnet and mainnet for future purposes :D

**Comment by A-Harby** [comment]
Just to be sure TFchain address for mainnet is the same as for testnet, right?

**Comment by rawdaGastan** [comment]
@A-Harby yes, if you have the account in those networks
