### ISSUE TITLE
monitor gridproxies

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_monitoring_bot#23]
on all envs, mainly by trying to get zos.system.version on any node on freefarm

**Comment by A-Harby** [comment]
Verified on release [v1.0.3](https://github.com/threefoldtech/tfgrid_monitoring_bot/releases/tag/v1.0.3).
bot working and monitoring gridproxies
![image](https://user-images.githubusercontent.com/109473873/216321267-f74578d3-d998-433b-b357-a9eafdd4bbf3.png)
![image](https://user-images.githubusercontent.com/109473873/216321605-54a4c9bc-8030-4b49-9624-b838a63b7bad.png)
