### ISSUE TITLE
behavior change: relay integration and proxy health check

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_monitoring_bot#27]
the health check was doing the following
- grid proxy api itself: reaching the gridproxy api e.g /farms /nodes to make sure the server is responding (there's a ping endpoint now too on the gridproxy)
-  random nodes connectivity to yggdrassil: by trying to proxy simple command like zos.system.version on nodes via the proxy

Now with the Relay integrated, nodes are reachable through the relay, and we removed the proxying features of ygg https://github.com/threefoldtech/tfgridclient_proxy/pull/292 so this will always fail in the current checks

So, let's keep the gridproxy api health check only and remove the nodes checks

https://github.com/threefoldtech/tf_operations/issues/1360

**Comment by A-Harby** [comment]
Verified.
with new twin relay changes, all functionality works fine.
![image](https://user-images.githubusercontent.com/109473873/223115902-2f5c498c-9adb-441a-abe1-f67a1969df78.png)
![image](https://user-images.githubusercontent.com/109473873/223116195-20615b38-fffe-4f3d-8e5e-4f71b99d9a5d.png)
