### ISSUE TITLE
monitoring bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_monitoring_bot#9]
- usage `tfgridmon --wallets wallets.json --env .envfile`

## env should have
- TESTNET_MNEMONIC 
- MAINNET_MNEMONIC
- TFTS_LIMIT='70000'
- BOT_TOKEN='telegram token'
- CHAT_ID= telegram chat id
- MINS='2' checks interval

## wallets.json
a simple json file having two lists for mainnet and testnet wallet addresses 
```
{ 
   "mainnet": [ ] ,
   "testnet": [ ] 
 
   }
```

should be written in golang

**Comment by A-Harby** [comment]
Verified,
I followed the steps to create telegram bot, then created `.env` and `'wallet.json` with info needed and then run `make build` and `bin/tfgridmon -e .env -w wallets.json`. 

Bot started to send me messages every minute as I specified, Which are warnings that my balance amount is less than threshold specified.
![image](https://user-images.githubusercontent.com/109473873/204516511-2f17452a-a643-43b9-8b03-95f74b2c849b.png)
